spring:
  datasource:
    username: postgres
    password: 321678
    url: jdbc:postgresql://localhost:5432/itrum
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

